version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Debug
before_build:
  - ps: $Env:PLATFORM_TOOLSET="v141"
after_build:
  - 7z a HW7.zip %APPVEYOR_BUILD_FOLDER%\Debug\*.* "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x86\ucrtbase.dll"

artifacts:  # Archive the generated packages in the ci.appveyor.com build report.  - path: bin\Debug\*
  - path: HW7.zip
    name: artifacts-all
